### ISSUE TITLE
Request for Winston draft

### ISSUE THREAD

**Issue by zoomzilla** [aeosynth/draft#113] opened 2015-05-06 22:02 UTC
Sorry if this isn't the right place for this, I was directed here.  Would it be possible to add a Winston draft feature to drafts.in?  There used to be a website that worked well for this but it's now defunct.

**Comment by aeosynth** [comment] 2015-05-07 01:39
dupe of #1 
yes, eventually

**Closed by aeosynth** 2015-05-07 01:39 UTC
